package com.populstay.populife.entity;


import android.os.Parcel;
import android.os.Parcelable;

import com.populstay.populife.home.entity.Home;


/**
 * 钥匙实体类
 */
public class Key implements Parcelable {

	private Long id;

	/**
	 * 用户 id
	 */
	private String userId;

	/**
	 * user type:110301-admin ekey, 110302-common user ekey
	 */
	private String userType;

	/**
	 * key status
	 * "110401"	Normal use
	 * "110402"	To be received
	 * "110405"	Frozen
	 * "110408"	deleted
	 * "110410"	Reset
	 * "110500" Expired
	 */
	private String keyStatus;

	/**
	 * 锁状态（0删除，1正常）
	 */
	private int status;


	/**
	 * lock id
	 */
	private int lockId;

	/**
	 * key id
	 */
	private int keyId;

	private int userKeyId;

//    /**
//     * judge whether it is an administrator
//     */
//    private boolean isAdmin;

	/**
	 * lock version information(json format)
	 */
	private String lockVersion;

	/**
	 * lock name
	 */
	private String lockName;

	/**
	 * lock alias
	 */
	private String lockAlias;

	/**
	 * lock mac
	 */
	private String lockMac;

	/**
	 * battery
	 */
	private int electricQuantity;

	/**
	 * lock flag position
	 */
	private int lockFlagPos;

	/**
	 * admin code, which only belongs to the admin ekey, will be used to verify the admin permission.
	 */
	private String adminPwd;

	/**
	 * The key data which will be used to unlock
	 */
	private String lockKey;

	/**
	 * Super passcode, which only belongs to the admin ekey, can be entered on the keypad to unlock
	 */
	private String noKeyPwd;

	/**
	 * Erasing passcode,which belongs to old locks, has been abandoned. Please don't use it.
	 */
	private String deletePwd;

	/**
	 * Initial data of passcode, which is generated by SDK, is used to create passcode
	 */
	private String pwdInfo;

	/**
	 * The timestamp which is generated by SDK during lock initializing time
	 */
	private long timestamp;

	/**
	 * aesKey
	 */
	private String aesKeyStr;

	/**
	 * The time when it becomes valid
	 */
	private long startDate;

	/**
	 * The time when it is expired
	 */
	private long endDate;

	/**
	 * characteristic value. it is used to indicate what kinds of feature do a lock support.
	 */
	private int specialValue;

	/**
	 * The offset between your time zone and UTC, in millisecond
	 */
	private int timezoneRawOffset;

	/**
	 * Is key authorized:0-NO,1-yes
	 */
	private int keyRight;

	/**
	 * Passcode version: 0、1、2、3、4
	 */
	private int keyboardPwdVersion;

	/**
	 * is support remote unlock: 1 - yes 、 2 - no
	 */
	private int remoteEnable;

	/**
	 * Comment
	 */
	private String remarks;

	/**
	 * Product model
	 */
	private String modelNum;

	/**
	 * Hardware version
	 */
	private String hardwareRevision;

	/**
	 * Firmware version
	 */
	private String firmwareRevision;


	private boolean isAllowRemoteUnlock;
	/**
	 * 钥匙的有效类型
	 * 1 限时
	 * 2 永久
	 * 3 单次
	 * 4 循环
	 */
	private Integer keyType;
	/**
	 * 钥匙的剩余有效天数
	 */
	private Integer dayNum;

	private boolean isAdmin;

	/**
	 * 空间分组
	 */
	private Home home;

	/**
	 * 锁当前时间，App自定义的临时字段
	 */
	private long lockCurrentTime;

	/**
	 * K1 ---曼哈顿开锁必备
	 */
	private String k1;

	/**
	 * K2 ---曼哈顿开锁必备
	 */
	private String k2;

    /**
     * KJX V3  lockData
     */
    private String lockData;

    public Key() {
	}

	public Key(Long id, String userId, String userType, String keyStatus, int lockId, int keyId,
			   String lockVersion, String lockName, String lockAlias, String lockMac, String lockData, int electricQuantity,
			   int lockFlagPos, String adminPwd, String lockKey, String noKeyPwd, String deletePwd,
			   String pwdInfo, long timestamp, String aesKeyStr, long startDate, long endDate, int specialValue,
			   int timezoneRawOffset, int keyRight, int keyboardPwdVersion, int remoteEnable, String remarks,
			   String modelNum, String hardwareRevision, String firmwareRevision, boolean isAllowRemoteUnlock,
			   Integer keyType, Integer dayNum, String k1, String k2) {
		this.id = id;
		this.userId = userId;
		this.userType = userType;
		this.keyStatus = keyStatus;
		this.lockId = lockId;
		this.keyId = keyId;
		this.lockVersion = lockVersion;
		this.lockName = lockName;
		this.lockAlias = lockAlias;
        this.lockMac = lockMac;
        this.lockData = lockData;
		this.electricQuantity = electricQuantity;
		this.lockFlagPos = lockFlagPos;
		this.adminPwd = adminPwd;
		this.lockKey = lockKey;
		this.noKeyPwd = noKeyPwd;
		this.deletePwd = deletePwd;
		this.pwdInfo = pwdInfo;
		this.timestamp = timestamp;
		this.aesKeyStr = aesKeyStr;
		this.startDate = startDate;
		this.endDate = endDate;
		this.specialValue = specialValue;
		this.timezoneRawOffset = timezoneRawOffset;
		this.keyRight = keyRight;
		this.keyboardPwdVersion = keyboardPwdVersion;
		this.remoteEnable = remoteEnable;
		this.remarks = remarks;
		this.modelNum = modelNum;
		this.hardwareRevision = hardwareRevision;
		this.firmwareRevision = firmwareRevision;
		this.isAllowRemoteUnlock = isAllowRemoteUnlock;
		this.keyType = keyType;
		this.dayNum = dayNum;
		this.k1 = k1;
		this.k2 = k2;
	}

	protected Key(Parcel in) {
		if (in.readByte() == 0) {
			id = null;
		} else {
			id = in.readLong();
		}
		userId = in.readString();
		userType = in.readString();
		keyStatus = in.readString();
		status = in.readInt();
		lockId = in.readInt();
		keyId = in.readInt();
		userKeyId = in.readInt();
		lockVersion = in.readString();
		lockName = in.readString();
		lockAlias = in.readString();
        lockMac = in.readString();
        lockData = in.readString();
		electricQuantity = in.readInt();
		lockFlagPos = in.readInt();
		adminPwd = in.readString();
		lockKey = in.readString();
		noKeyPwd = in.readString();
		deletePwd = in.readString();
		pwdInfo = in.readString();
		timestamp = in.readLong();
		aesKeyStr = in.readString();
		startDate = in.readLong();
		endDate = in.readLong();
		specialValue = in.readInt();
		timezoneRawOffset = in.readInt();
		keyRight = in.readInt();
		keyboardPwdVersion = in.readInt();
		remoteEnable = in.readInt();
		remarks = in.readString();
		modelNum = in.readString();
		hardwareRevision = in.readString();
		firmwareRevision = in.readString();
		isAllowRemoteUnlock = in.readByte() != 0;
		if (in.readByte() == 0) {
			keyType = null;
		} else {
			keyType = in.readInt();
		}
		if (in.readByte() == 0) {
			dayNum = null;
		} else {
			dayNum = in.readInt();
		}
		isAdmin = in.readByte() != 0;
		home = in.readParcelable(Home.class.getClassLoader());//Home.class.getClassLoader()
		lockCurrentTime = in.readLong();
		k1 = in.readString();
		k2 = in.readString();
	}

	public static final Creator<Key> CREATOR = new Creator<Key>() {
		@Override
		public Key createFromParcel(Parcel in) {
			return new Key(in);
		}

		@Override
		public Key[] newArray(int size) {
			return new Key[size];
		}
	};

	public int getUserKeyId() {
		return userKeyId;
	}

	public void setUserKeyId(int userKeyId) {
		this.userKeyId = userKeyId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getLockId() {
		return this.lockId;
	}

	public void setLockId(int lockId) {
		this.lockId = lockId;
	}

	public String getLockVersion() {
		return lockVersion;
	}

	public void setLockVersion(String lockVersion) {
		this.lockVersion = lockVersion;
	}

	public String getDeletePwd() {
		return this.deletePwd;
	}

	public void setDeletePwd(String deletePwd) {
		this.deletePwd = deletePwd;
	}

	public String getPwdInfo() {
		return this.pwdInfo;
	}

	public void setPwdInfo(String pwdInfo) {
		this.pwdInfo = pwdInfo;
	}

	public long getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(long timestamp) {
		this.timestamp = timestamp;
	}

	public String getLockName() {
		return this.lockName;
	}

	public void setLockName(String lockName) {
		this.lockName = lockName;
	}

	public String getLockMac() {
		return this.lockMac;
	}

	public void setLockMac(String lockMac) {
		this.lockMac = lockMac;
	}

	public int getLockFlagPos() {
		return this.lockFlagPos;
	}

	public void setLockFlagPos(int lockFlagPos) {
		this.lockFlagPos = lockFlagPos;
	}

	public int getKeyId() {
		return this.keyId;
	}

	public void setKeyId(int keyId) {
		this.keyId = keyId;
	}

	public boolean isAdmin() {
		return  isAdmin;
		//return "110301".equals(userType);
	}
	public void isAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public long getStartDate() {
		return this.startDate;
	}

	public void setStartDate(long startDate) {
		this.startDate = startDate;
	}

	public long getEndDate() {
		return this.endDate;
	}

	public void setEndDate(long endDate) {
		this.endDate = endDate;
	}

	public int getSpecialValue() {
		return this.specialValue;
	}

	public void setSpecialValue(int specialValue) {
		this.specialValue = specialValue;
	}

	public int getTimezoneRawOffset() {
		return this.timezoneRawOffset;
	}

	public void setTimezoneRawOffset(int timezoneRawOffset) {
		this.timezoneRawOffset = timezoneRawOffset;
	}

	public String getHardwareRevision() {
		return this.hardwareRevision;
	}

	public void setHardwareRevision(String hardwareRevision) {
		this.hardwareRevision = hardwareRevision;
	}

	public String getFirmwareRevision() {
		return this.firmwareRevision;
	}

	public void setFirmwareRevision(String firmwareRevision) {
		this.firmwareRevision = firmwareRevision;
	}

	public String getLockAlias() {
		return this.lockAlias;
	}

	public void setLockAlias(String lockAlias) {
		this.lockAlias = lockAlias;
	}

	public String getKeyStatus() {
		return this.keyStatus;
	}

	public void setKeyStatus(String keyStatus) {
		this.keyStatus = keyStatus;
	}

	public int getElectricQuantity() {
		return electricQuantity;
	}

	public void setElectricQuantity(int electricQuantity) {
		this.electricQuantity = electricQuantity;
	}

	public String getAdminPwd() {
		return adminPwd;
	}

	public void setAdminPwd(String adminPwd) {
		this.adminPwd = adminPwd;
	}

	public String getLockKey() {
		return lockKey;
	}

	public void setLockKey(String lockKey) {
		this.lockKey = lockKey;
	}

	public String getNoKeyPwd() {

		return noKeyPwd;

	}

	public void setNoKeyPwd(String noKeyPwd) {
		this.noKeyPwd = noKeyPwd;
	}

	public String getAesKeyStr() {
		return aesKeyStr;
	}

	public void setAesKeyStr(String aesKeyStr) {
		this.aesKeyStr = aesKeyStr;
	}

	public String getModelNum() {
		return modelNum;
	}

	public void setModelNum(String modelNum) {
		this.modelNum = modelNum;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public int getKeyRight() {
		return keyRight;
	}

	public void setKeyRight(int keyRight) {
		this.keyRight = keyRight;
	}

	public int getKeyboardPwdVersion() {
		return keyboardPwdVersion;
	}

	public void setKeyboardPwdVersion(int keyboardPwdVersion) {
		this.keyboardPwdVersion = keyboardPwdVersion;
	}

	public int getRemoteEnable() {
		return remoteEnable;
	}

	public void setRemoteEnable(int remoteEnable) {
		this.remoteEnable = remoteEnable;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public void setK1(String k1) {
		this.k1 = k1;
	}

	public String getK1() {
		return k1;
	}

	public void setK2(String k2) {
		this.k2 = k2;
	}

	public String getK2() {
		return k2;
	}


	@Override
	public String toString() {
		return "Key{" +
				"id=" + id +
				", userType='" + userType + '\'' +
				", keyStatus='" + keyStatus + '\'' +
				", lockId=" + lockId +
				", keyId=" + keyId +
				", lockVersion='" + lockVersion + '\'' +
				", lockName='" + lockName + '\'' +
				", k1='" + k1 + '\'' +
				", k2='" + k2 + '\'' +
				", lockAlias='" + lockAlias + '\'' +
                ", lockMac='" + lockMac + '\'' +
                ", lockData='" + lockData + '\'' +
				", electricQuantity=" + electricQuantity +
				", lockFlagPos=" + lockFlagPos +
				", adminPwd='" + adminPwd + '\'' +
				", lockKey='" + lockKey + '\'' +
				", noKeyPwd='" + noKeyPwd + '\'' +
				", deletePwd='" + deletePwd + '\'' +
				", pwdInfo='" + pwdInfo + '\'' +
				", timestamp=" + timestamp +
				", aesKeyStr='" + aesKeyStr + '\'' +
				", startDate=" + startDate +
				", endDate=" + endDate +
				", specialValue=" + specialValue +
				", timezoneRawOffset=" + timezoneRawOffset +
				", keyRight=" + keyRight +
				", keyboardPwdVersion=" + keyboardPwdVersion +
				", remoteEnable=" + remoteEnable +
				", remarks='" + remarks + '\'' +
				", modelNum='" + modelNum + '\'' +
				", hardwareRevision='" + hardwareRevision + '\'' +
				", firmwareRevision='" + firmwareRevision + '\'' +
				", isAllowRemoteUnlock=" + isAllowRemoteUnlock +
				'}';
	}

	public boolean isAllowRemoteUnlock() {
		return isAllowRemoteUnlock;
	}

	public void setAllowRemoteUnlock(boolean allowRemoteUnlock) {
		isAllowRemoteUnlock = allowRemoteUnlock;
	}

	public Integer getDayNum() {
		return this.dayNum;
	}

	public void setDayNum(Integer dayNum) {
		this.dayNum = dayNum;
	}

	public Integer getKeyType() {
		return this.keyType;
	}

	public void setKeyType(Integer keyType) {
		this.keyType = keyType;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Home getHome() {
		return home;
	}

	public void setHome(Home home) {
		this.home = home;
	}

	public long getLockCurrentTime() {
		return lockCurrentTime;
	}

	public void setLockCurrentTime(long lockCurrentTime) {
		this.lockCurrentTime = lockCurrentTime;
	}

    public String getLockData() {
        return lockData;
    }

    public void setLockData(String lockData) {
        this.lockData = lockData;
    }

    @Override
	public int describeContents() {
		return 0;
	}

	@Override
	public void writeToParcel(Parcel dest, int flags) {
		if (id == null) {
			dest.writeByte((byte) 0);
		} else {
			dest.writeByte((byte) 1);
			dest.writeLong(id);
		}
		dest.writeString(userId);
		dest.writeString(userType);
		dest.writeString(keyStatus);
		dest.writeInt(status);
		dest.writeInt(lockId);
		dest.writeInt(keyId);
		dest.writeInt(userKeyId);
		dest.writeString(lockVersion);
		dest.writeString(lockName);
		dest.writeString(lockAlias);
        dest.writeString(lockMac);
        dest.writeString(lockData);
		dest.writeInt(electricQuantity);
		dest.writeInt(lockFlagPos);
		dest.writeString(adminPwd);
		dest.writeString(lockKey);
		dest.writeString(noKeyPwd);
		dest.writeString(deletePwd);
		dest.writeString(pwdInfo);
		dest.writeLong(timestamp);
		dest.writeString(aesKeyStr);
		dest.writeLong(startDate);
		dest.writeLong(endDate);
		dest.writeInt(specialValue);
		dest.writeInt(timezoneRawOffset);
		dest.writeInt(keyRight);
		dest.writeInt(keyboardPwdVersion);
		dest.writeInt(remoteEnable);
		dest.writeString(remarks);
		dest.writeString(modelNum);
		dest.writeString(hardwareRevision);
		dest.writeString(firmwareRevision);
		dest.writeByte((byte) (isAllowRemoteUnlock ? 1 : 0));
		if (keyType == null) {
			dest.writeByte((byte) 0);
		} else {
			dest.writeByte((byte) 1);
			dest.writeInt(keyType);
		}
		if (dayNum == null) {
			dest.writeByte((byte) 0);
		} else {
			dest.writeByte((byte) 1);
			dest.writeInt(dayNum);
		}
		dest.writeByte((byte) (isAdmin ? 1 : 0));
		dest.writeParcelable(home, flags);
		dest.writeLong(lockCurrentTime);
		dest.writeString(k1);
		dest.writeString(k2);
	}
}
